name: Deployment to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v3

      - name: 2. Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 3. Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jamal-be:latest

      - name: 4. SSH to VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Pull image terbaru dari Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/jamal-be:latest

            # Stop dan remove container lama
            docker stop jamal-be || true
            docker rm jamal-be || true

            # Jalanin container baru dari image yang baru di-pull
            docker run -d \
              --name jamal-be \
              -p 3000:3000 \
              --restart always \
              --env-file /home/deployer/jamal-be/.env.production \
              ${{ secrets.DOCKERHUB_USERNAME }}/jamal-be:latest

            # Hapus image lama yang gak kepake
            docker image prune -f
